//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp8.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblExam
    {
        public int examId { get; set; }
        public string examName { get; set; }
        public string examMark { get; set; }
        public string examDate { get; set; }
        public Nullable<int> stuId { get; set; }
        public Nullable<int> couId { get; set; }
    
        public virtual tblCourse tblCourse { get; set; }
        public virtual tblStudent tblStudent { get; set; }
    }
}
